### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by huangboju** [wangshub/Alfred-Gitlab-Tool#5]
![image](https://user-images.githubusercontent.com/14818224/49630009-4c906480-fa27-11e8-885f-9155780d0a31.png)

**Comment by wangshub** [comment]
@huangboju 你应该是没有设置好 gitlab api url 和 token

**Comment by huangboju** [comment]
@wangshub 我设置了的
https://code.devops.xxxxx 我的域名是这样开头的可以吗？

**Comment by wangshub** [comment]
@huangboju 

![image](https://user-images.githubusercontent.com/20924010/49684089-d153af00-fb09-11e8-8616-a8222e74e3ab.png)

api 地址需要以 api/v4 或者 api/v3 结尾

**Comment by huangboju** [comment]
@wangshub 不是api/v4 和api/v3的就用不了吗
我可以自定义吗

**Comment by wangshub** [comment]
@huangboju 这个 Workflow 只是针对 Gitlab 的服务，而 Gitlab 的 API 接口就只是这样的哦

**Comment by huangboju** [comment]
@wangshub 那就是自己服务器上的gitlab用不了？

**Comment by wangshub** [comment]
@huangboju 可以使用 
![image](https://user-images.githubusercontent.com/20924010/49787093-b3cc5280-fd60-11e8-9523-eae9456dbe15.png)

**Comment by wangshub** [comment]
@huangboju 截图已经很清楚了

**Comment by huangboju** [comment]
@wangshub 谢谢，我知道是哪里出问题了。
https://*****.com/dashboard/merge_requests?assignee_id=****&state=opened
我的那个接口是这样的，直接用你的那个似乎不可，我需要修改一下

**Comment by wangshub** [comment]
@huangboju nice
